wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    environment:
      - SYMFONY__ENV__TWOFACTOR_AUTH=false
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.9:8765
    volumes:
      - /volume1/docker/wallabag/images:/var/www/wallabag/web/assets/images
    ports:
      - 8765:80
    restart: always