version: "3"
services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        ports:
            - "1423:80"
        volumes:
            - ./data:/data/
