---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /volume1/docker/homer/assets/:/www/assets
    ports:
      - 8057:8080
    environment:
      - UID=1026
      - GID=100
    restart: unless-stopped